# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399dcef2f96f00d1d6d835dc719d98ac072207f5a688a0a0527c266bb2575eae4f68c7024bed43d4a9c08508a4fa0fa6a0b5cf1d2ed5e95ba8a500d4c15b700f

test:
  secret_key_base: 0bb8d7de5eaca88aeaf7b7d27e2612bce419908007dda371edc817d4d1b3551f0073395ac4442c5adf8a6975ab4547caca7319b1a200f53db74bd4fb09711196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
